---
title: "Psy524 Lab #2 R code"
author: "Your Name"
output:
  word_document: default
  html_notebook: default
---

# Psy524 Lab #2 Question 5

```{r Packages}
install.packages("foreign")
library(foreign)
```

```{r Loading Data}
forclass <- read.spss("https://github.com/AndrewAinsworth/psy524/raw/master/LabAssignments/Lab02/forclass.sav", 
                       use.value.label=TRUE, 
                       to.data.frame=TRUE)
names(forclass) <- tolower(names(forclass))
```

# Computing Mahalanobis Distances and Checking for Multivariate outliers
```{r Mahalanobis}
mahal <- mahalanobis(forclass[ , -c(1:3)], 
                     colMeans(forclass[ ,-c(1:3)], na.rm = TRUE), 
                     cov(forclass[ , -c(1:3)], use = "pairwise.complete.obs"))
cutoff <- qchisq(.999, ncol(forclass[ , -c(1:2)]))
summary(mahal < cutoff)
```
# Simple normality and linearity
```{r Normality and Simple linearity}
#Panel Plot of histrograms for the first 4 variables
distribution1 <- par(mfrow=c(2,2))
distribution1 <- hist(forclass$sos)
distribution1 <- hist(forclass$ego)
distribution1 <- hist(forclass$n)
distribution1 <- hist(forclass$e)

#Panel Plot of histrograms for the first 4 variables
distribution2 <- par(mfrow=c(2,2))
distribution2 <- hist(forclass$o)
distribution2 <- hist(forclass$a)
distribution2 <- hist(forclass$c)
distribution2 <- hist(forclass$soitot)

#Simple plot separated by gender predicting SOITOT by A
plot(forclass$sos, forclass$soitot,
     col = forclass$gender,
     xlab = "SOS",
     ylab = "SOITOT score",
     main="Prediction of SOITOT by SOS")
abline(lm(soitot ~ sos, data = forclass), col="black")
```

# Testing for Multicollinearity
```{r Multicollinearity}
#We can look at the correlations
correlation <- cor(forclass[ , -c(1:2)], use = "pairwise.complete.obs")
View(correlation)
symnum(correlation)
```
# More Linearity and Homoskedasticity
```{r Linearity and Homoskedasticity}
#In order to check normality in regression we have to run a model first
model = lm(soitot ~ sos + ego + n + e + o + a + c, data = forclass)
fitted = scale(model$fitted.values)
standardized = rstudent(model)

#Q-Q Plot of standardized values
qqnorm(standardized)
abline(0,1)

#Histogram of standardized fitted values
hist(standardized)

#Removing Linear Trend to check for homoskedasticity
plot(fitted, standardized)
abline(0,0)
abline(v = 0)
```

